"""
pdf_generator.py

Converts the markdown business report to PDF using:
    markdown (text -> HTML)  ->  xhtml2pdf (pure-Python, reportlab-based)


"""

import io
import markdown as md_lib
from xhtml2pdf import pisa

_CSS = """
<style>
@page { size: A4 landscape; margin: 18mm 16mm; }
body { font-family: Helvetica, Arial, sans-serif; color: #1a1a2e; font-size: 10.5pt; }
h1 { color: #0aa; font-size: 20pt; margin-bottom: 4px; }
h2 { color: #0891b2; font-size: 14pt; border-bottom: 1px solid #cbd5e1; padding-bottom: 2px; margin-top: 18px; }
h3 { color: #2563eb; font-size: 12pt; margin-top: 14px; }
h4 { color: #4338ca; font-size: 11pt; }
p  { line-height: 1.45; }
table { border-collapse: collapse; width: 100%; margin: 10px 0 16px; }
th, td { border: 1px solid #94a3b8; padding: 5px 8px; text-align: left; font-size: 9.5pt; }
th { background: #0f172a; color: #00f5ff; }
ul, ol { margin: 4px 0 10px 18px; }
li { margin-bottom: 3px; line-height: 1.4; }
hr { border: none; border-top: 1px solid #cbd5e1; margin: 14px 0; }
strong { color: #0f172a; }
.subtitle { color: #64748b; font-size: 9pt; margin-bottom: 14px; }
</style>
"""


def generate_pdf_bytes(report_text: str, dataset_name: str) -> bytes:
    body_html = md_lib.markdown(
        report_text or "",
        extensions=["tables", "fenced_code", "sane_lists"],
    )

    full_html = f"""
    <html><head><meta charset="utf-8">{_CSS}</head><body>
        <h1>{dataset_name} — Business Performance Report</h1>
        <div class="subtitle">Generated by AI Data Analyzer</div>
        {body_html}
    </body></html>
    """

    buffer = io.BytesIO()
    result = pisa.CreatePDF(src=full_html, dest=buffer, encoding='utf-8')
    if result.err:
        raise RuntimeError(f"PDF generation failed with {result.err} error(s)")
    return buffer.getvalue()